name: less_dart
version: 2.0.0
author: Adalberto Lacruz <adalberto.lacruz@gmail.com>
description: Native Dart Less compiler/transformer to build .css files from .less files.
homepage: https://github.com/AdalbertoLacruz/less_dart
environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'
dependencies:
  build: '>=0.12.7 <0.13.0'
  build_config: '>=0.3.1 <0.4.0'
  meta: '>=1.0.4 <2.0.0'
  mime: '>=0.9.0 <0.12.0'
  package_resolver: ">=1.0.2 < 2.0.0"
  path: '>=1.4.1 <2.0.0'
  source_maps: '>=0.10.2 <0.12.0'
  source_span: '>=1.4.0 <2.0.0'
  utf: '>=0.9.0 <0.12.0'
dev_dependencies:
  logging: '>=0.11.0 <0.12.0'
  mockito: '>=1.0.0 <4.0.0'
  stack_trace: '>=1.7.2 <2.0.0'
  test: '>=0.12.20+2 <2.0.0'
