name: less_dart
version: 0.1.0
author: Adalberto Lacruz <adalberto.lacruz@gmail.com>
description: Native Dart Less transformer to build .css files from .less files.
homepage: https://github.com/AdalbertoLacruz/less_dart
dependencies:
  barback: '>=0.13.0 <0.16.0'
  utf: '>=0.9.0 <0.12.0'
dev_dependencies:
  unittest: '>=0.9.0 <0.12.0'
