name: less_dart
version: 1.1.0
author: Adalberto Lacruz <adalberto.lacruz@gmail.com>
description: Native Dart Less compiler/transformer to build .css files from .less files.
homepage: https://github.com/AdalbertoLacruz/less_dart
environment:
  sdk: '>=1.22.0 <2.0.0'
dependencies:
  barback: '>=0.15.2+9 <0.16.0'
  meta: '>=1.0.4 <2.0.0'
  mime: '>=0.9.0 <0.12.0'
  package_resolver: ">=1.0.2 < 2.0.0"
  path: '>=1.4.1 <2.0.0'
  source_maps: '>=0.10.2 <0.12.0'
  utf: '>=0.9.0 <0.12.0'
dev_dependencies:
  logging: '>=0.11.0 <0.12.0'
  mockito: '>=1.0.0 <3.0.0'
  stack_trace: '>=1.7.2 <2.0.0'
  test: '>=0.12.20+2 <0.13.0'
