name: less_dart
version: 1.0.0
author: Adalberto Lacruz <adalberto.lacruz@gmail.com>
description: Native Dart Less compiler/transformer to build .css files from .less files.
homepage: https://github.com/AdalbertoLacruz/less_dart
environment:
  sdk: '>=1.21.1 <2.0.0'
dependencies:
  barback: '>=0.13.0 <0.16.0'
  mime: '>=0.9.0 <0.12.0'
  path: '>=1.3.0 <2.0.0'
  source_maps: '>=0.10.0 <0.12.0'
  utf: '>=0.9.0 <0.12.0'
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
